name: allnotes
description: "A take note app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # to i18n
  flutter_localizations:
    sdk: flutter
  # di(dependency injection)
  get_it: ^7.6.7
  # compare objects (equals())
  equatable: ^2.0.5
  # let ypu make a return between two different objects
  dartz: ^0.10.1
  # state management
  flutter_bloc: ^8.1.3
  # screen util for responsive
  flutter_screenutil: ^5.9.0
  go_router: ^13.0.1
  # firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logos/
    - assets/languages/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
